upgrade secrets yaml

diff --git a/.github/workflows/eks-reusable-k8s-deploy-sec.yaml b/.github/workflows/eks-reusable-k8s-deploy-sec.yaml
--- a/.github/workflows/eks-reusable-k8s-deploy-sec.yaml
+++ b/.github/workflows/eks-reusable-k8s-deploy-sec.yaml
@@ -22,10 +22,10 @@ on:
       environment:
         required: true
         type: string
-      secrets_list:
+      includes:
         required: true
         type: string
-      secrets_name:
+      name:
         required: true
         type: string
 
@@ -49,24 +49,52 @@ jobs:
         run: |
           aws eks update-kubeconfig --region ${{ inputs.aws-region }} --name ${{ inputs.cluster-name }}
 
-      - name: Create Kubernetes Secrets
-        env: 
-          input_json: ${{ toJson(secrets) }}
-          secrets_list: ${{ inputs.secrets_list }}
-          environment: ${{ inputs.environment }}
-          namespace: ${{ inputs.namespace }}
-          k8secname: ${{ inputs.secrets_name }}
+      - name: 'Setup: Create yaml file'
         run: |
-          IFS=',' read -ra secrets_array <<< "$secrets_list"
-          create=("kubectl" "create" "-n $namespace" "secret" "generic" "$k8secname")
-          delete=("kubectl" "delete" "-n $namespace" "secret" "--ignore-not-found" "$k8secname")
-          for secret_key in "${secrets_array[@]}"; do
-            if [[ $input_json == *"$secret_key"* ]]; then
-              secret_value=$(echo "$input_json" | jq -r ".$secret_key")
-              create+=("--from-literal=""$secret_key=$secret_value")
-            fi
+          cat <<EOF > secret.yaml
+          apiVersion: v1
+          kind: Secret
+          metadata:
+            name: ${{ inputs.name }}
+            namespace: ${{ inputs.namespace }}
+          type: Opaque
+          stringData:
+          EOF
+
+      - name: 'Setup: Extract secrets and append to yaml'
+        env:
+          SECRETS_JSON: ${{ toJson(secrets) }}
+        run: |
+          keys=${{ inputs.includes }}
+          for key in ${keys//,/ }
+          do
+              value=$(echo "$SECRETS_JSON" | jq -r ".$key")
+              if [[ "$value" == "null" ]]; then
+                  echo "$key not found in GitHub secrets. Abort!"
+                  exit 1
+              fi
+              echo "Found: $key"
+              echo -e "  $key: \"$value\"\n" >> secret.yaml
           done
-          echo "${create[@]}"
-          ${delete[@]}
-          ${create[@]}
+
+      # - name: Create Kubernetes Secrets
+      #   env: 
+      #     input_json: ${{ toJson(secrets) }}
+      #     secrets_list: ${{ inputs.secrets_list }}
+      #     environment: ${{ inputs.environment }}
+      #     namespace: ${{ inputs.namespace }}
+      #     k8secname: ${{ inputs.secrets_name }}
+      #   run: |
+      #     IFS=',' read -ra secrets_array <<< "$secrets_list"
+      #     create=("kubectl" "create" "-n $namespace" "secret" "generic" "$k8secname")
+      #     delete=("kubectl" "delete" "-n $namespace" "secret" "--ignore-not-found" "$k8secname")
+      #     for secret_key in "${secrets_array[@]}"; do
+      #       if [[ $input_json == *"$secret_key"* ]]; then
+      #         secret_value=$(echo "$input_json" | jq -r ".$secret_key")
+      #         create+=("--from-literal=""$secret_key=$secret_value")
+      #       fi
+      #     done
+      #     echo "${create[@]}"
+      #     ${delete[@]}
+      #     ${create[@]}
 
